### ISSUE TITLE
Error using edivisive

### ISSUE THREAD

**Issue by angus-c** [mongodb/signal-processing-algorithms#19]
Hi!

When I try to run a simple e-divisive example I'm getting a dependency error.
I'm new to python package infrastructure so it's possible I did a bad install (I used pip)

Code
```
from signal_processing_algorithms.energy_statistics import energy_statistics
series = [1,2,3,4]

change_points = energy_statistics.e_divisive(series, pvalue=0.01, permutations=100)
```

Error
```
Traceback (most recent call last):
  File "/Users/me/Library/Python/3.8/lib/python/site-packages/signal_processing_algorithms/energy_statistics/cext_calculator.py", line 20, in <module>
    LIB_E_DIVISIVE = np.ctypeslib.load_library("_e_divisive", so_path)
  File "/Users/me/Library/Python/3.8/lib/python/site-packages/numpy/ctypeslib.py", line 153, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
Traceback (most recent call last):
  File "edivisive-tester.py", line 1, in <module>
    from signal_processing_algorithms.energy_statistics import energy_statistics
  File "/Users/me/Library/Python/3.8/lib/python/site-packages/signal_processing_algorithms/energy_statistics/energy_statistics.py", line 9, in <module>
    from signal_processing_algorithms.energy_statistics.cext_calculator import (
ImportError: cannot import name 'calculate_distance_matrix' from 'signal_processing_algorithms.energy_statistics.cext_calculator' (/Users/me/Library/Python/3.8/lib/python/site-packages/signal_processing_algorithms/energy_statistics/cext_calculator.py)
```

Python 3.8.2
signal-processing-algorithms 2.0.0

**Comment by uglycoyote** [comment]
I'm also getting the same thing, any solution?

**Comment by angus-c** [comment]
IIRC I removed the C++ portion of the code.

**Comment by vimiix** [comment]
I got the same error. 

Downgrade the version of poetry to [1.3.2](https://github.com/mongodb/signal-processing-algorithms/blob/master/.github/workflows/cicd.yml#L25) can fix this, then run:

```
poetry build
```

It will generate a `whl` package corresponding to the python version in the current directory
